import React, { useState } from "react";
import { SiAuthy } from "react-icons/si";
import { Link } from "react-router-dom";
import axios from "axios";
import { useEffect } from "react";
function Enable() {

  const [loading, setLoading] = useState(false);
  const [qr,setQr] =useState("");
  useEffect(() => {
    const fetchDepositData = async () => {
      try {
        setLoading(true);
        const token = localStorage.getItem("token");
        const header = {
          token: token,
        };

        const response = await axios.get(
          "http://127.0.0.1:8000/adminpanel/getQr/",
          {
            headers: header,
          }
        );

        setQr(response.data.qr);
        //console.log(response);
      } catch (e) {
        // console.log(e);
      } finally {
        setLoading(false);
      }
    };

    fetchDepositData();
  }, []);

  

  return (<>
  {loading ? (
        <div
          className={`w-full h-full flex justify-center min-h-screen md:min-h-screen items-center ${
            loading ? "block" : "hidden"
          }`}
        >
          <div className="w-16 h-16 rounded-full border-t-4 border-blue-500 border-solid animate-spin" />
        </div>
      ) : (
    <div className="min-h-screen ">
      <div className="mb-10 mt-44 md:my-32 relative font-georgia  mx-2 md:mx-10 ">
        <div className="text-2xl md:text-5xl  flex">
          <span className="mt-1 mr-2">
            <SiAuthy />
          </span>{" "}
          Enable Two-Factor{" "}
          <span className="text-violet-600"> Authentication</span>
        </div>
        <div className=" mt-10 mx-3 md:mx-10">
          <ul className="text-gray-900 md:text-md text-base">
            <li>
              <div className="md:text-2xl text-black text-lg">
                Follow these steps to enable Two-Factor Authentication
              </div>
            </li>
            <li className="mt-5 ">
              1. Download a two-factor authentication app like Google
              Authenticator on your mobile device if you haven't already.
            </li>
            <li>2. Scan the below QR code into your authentication app.</li>
            <li>3. Click the 'Verify' button to continue.</li>
            <li>4. Enter the verification code generated by the app.</li>
            <li>
              5. Two-factor authentication is now enabled for your account.
            </li>
          </ul>
        </div>
        <div className="mt-10 md:mx-5">
          <div className="font-georgia text-2xl w-44 md:w-52 text-violet-600">
            <img
              src={`data:image/png;base64,${qr}`}
              alt=""
              className="w-44 md:w-52  "
            />
          </div>
        </div>
        <div className="md:mx-10 md:mt-5">
        <Link to="/verify-authy" className="font-georgia px-3 py-2 text-white rounded-md shadow-inner bg-violet-600" >
          Proceed To Verify
          </Link>  
        </div>
      </div>
    </div>
    )}
    </>
  );
}

export default Enable;
